[package]
name="avif-decoder_dep"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { path = "../image-rs" , features = ["avif-native"] }

[target.'cfg(any(target_arch = "x86",target_arch = "x86_64"))'.dependencies.image]
path = "../image-rs"
default-features = false
features = ["nasm"]
